name: smf_workspace
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

workspace:
  - packages/smf_hooks
  - packages/smf_engine
  - packages/smf_cli

dev_dependencies:
  melos: ^8.2.2
  path: ^1.9.1
  very_good_analysis: 10.3.0

melos:
  repository: https://github.com/Ventairy/smf
  scripts:
    format:
      run: dart run tool/check_dart_format.dart --write
    format:check:
      run: dart run tool/check_dart_format.dart
    analyze:
      run: dart analyze --fatal-infos
    docs:check:
      run: dart run tool/check_markdown_links.dart
    test:
      exec:
        command: dart test
        concurrency: 1
      packageFilters:
        dirExists: test
    gen:
      exec:
        command: dart run build_runner build
        concurrency: 1
      packageFilters:
        dependsOn: build_runner
    publish:dry-run:
      exec:
        command: dart pub publish --dry-run
        concurrency: 1
